### PR TITLE
feat: add aria2

### PR DESCRIPTION
**Pull request by oElberte**

### CODE REVIEW

**Comment by SanujaNS** [comment]
This is interesting. Is this working?

**Comment by oElberte** [comment]
> This is interesting. Is this working?

Yes, I just can’t guarantee with docker and kubernetes, but I’ve added aria2 in the apk.txt so they can use. I went from 500KB/s to 10MB/s.

**Comment by BennyThink** [comment]
This seems like a know issue from yt-dlp https://github.com/yt-dlp/yt-dlp/issues/6369

I tried daily build, and it's back to normal. Can you add an environment to control this behavior, i.e.

```python
if os.getenv("ENABLE_ARIA2"):
    ydl_opts.update(
        external_downloader="aria2c",
        external_downloader_args=[....]
    )
```

**Review by BennyThink — CHANGES_REQUESTED** [review]
use env to control downloader behavior

**Pull request merged**
